

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: linkedin_pass
      MYSQL_DATABASE: linkedin_db
    ports:
      - "3307:3306"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
