services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL="mysql+pymysql://linkedin_user:linkedin_pass@db/linkedin_db"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: linkedin_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
