"""Initial migration

Revision ID: a9243c4d5539
Revises: c34bfc774754
Create Date: 2025-03-19 13:34:09.254089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a9243c4d5539'
down_revision: Union[str, None] = 'c34bfc774754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkedin_pages', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('linkedin_pages', 'url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.drop_index('page_id', table_name='linkedin_pages')
    op.create_unique_constraint(None, 'linkedin_pages', ['url'])
    op.drop_column('linkedin_pages', 'specialities')
    op.drop_column('linkedin_pages', 'page_id')
    op.drop_column('linkedin_pages', 'website')
    op.drop_column('linkedin_pages', 'profile_picture')
    op.drop_column('linkedin_pages', 'description')
    op.drop_column('linkedin_pages', 'industry')
    op.drop_column('linkedin_pages', 'head_count')
    op.drop_column('linkedin_pages', 'total_followers')
    op.add_column('posts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('posts', 'linkedin_page_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'posts', 'linkedin_pages', ['linkedin_page_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'social_media_users', 'linkedin_pages', ['page_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_media_users', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.alter_column('posts', 'linkedin_page_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('posts', 'created_at')
    op.add_column('linkedin_pages', sa.Column('total_followers', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('linkedin_pages', sa.Column('head_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('linkedin_pages', sa.Column('industry', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('linkedin_pages', sa.Column('description', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('linkedin_pages', sa.Column('profile_picture', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('linkedin_pages', sa.Column('website', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('linkedin_pages', sa.Column('page_id', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('linkedin_pages', sa.Column('specialities', mysql.VARCHAR(length=500), nullable=True))
    op.drop_constraint(None, 'linkedin_pages', type_='unique')
    op.create_index('page_id', 'linkedin_pages', ['page_id'], unique=True)
    op.alter_column('linkedin_pages', 'url',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('linkedin_pages', 'created_at')
    # ### end Alembic commands ###
