"""Initial migration

Revision ID: aaa419589e16
Revises: a9243c4d5539
Create Date: 2025-03-19 13:46:04.664539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aaa419589e16'
down_revision: Union[str, None] = 'a9243c4d5539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_social_media_users_id', table_name='social_media_users')
    op.drop_index('user_id', table_name='social_media_users')
    op.drop_table('social_media_users')
    op.drop_table('posts')
    op.drop_index('url', table_name='linkedin_pages')
    op.create_index(op.f('ix_linkedin_pages_id'), 'linkedin_pages', ['id'], unique=False)
    op.drop_column('linkedin_pages', 'created_at')
    op.drop_column('linkedin_pages', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkedin_pages', sa.Column('url', mysql.VARCHAR(length=500), nullable=False))
    op.add_column('linkedin_pages', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_linkedin_pages_id'), table_name='linkedin_pages')
    op.create_index('url', 'linkedin_pages', ['url'], unique=True)
    op.create_table('posts',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('linkedin_page_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('content', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('likes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('comments_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_table('social_media_users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('profile_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('page_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_index('user_id', 'social_media_users', ['user_id'], unique=True)
    op.create_index('ix_social_media_users_id', 'social_media_users', ['id'], unique=False)
    # ### end Alembic commands ###
